version: '3.7'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./src:/var/www
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 9000:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-db:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    networks:
      app_net:
        ipv4_address: 172.30.0.4

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      app_net:
        ipv4_address: 172.30.0.5

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    networks:
      app_net:
        ipv4_address: 172.30.0.6

volumes:
  mysql-db:
    driver: local
  redis-data:
    driver: local

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24